---
name: Create GitHub Caches for default branch

on:
  push:
    branches:
      - main
jobs:
  cache-asdf-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - name: Checkout voxel51/aloha-github-workflows
        uses: actions/checkout@v6.0.1
        with:
          repository: voxel51/aloha-github-workflows
          ref: main
          token: ${{ secrets.ORG_RO_ALOHA_GITHUB_WORKFLOWS_FG_PAT }}
          path: ./.github/actions/aloha-github-workflows
      - name: Set generate-version-file action's path from remote to local
        # Public repos cannot access private action repo without GitHub Enterprise
        # Instead, we clone the private workflow directory and update the `asdf-install-and-cache/action.yml`
        # file's reference to `voxel51/aloha-github-workflows/.github/actions/generate-version-file` with the local path.
        shell: bash
        run: |
          sed -i \
            's%voxel51/aloha-github-workflows/.github/actions/generate-version-file@main%./.github/actions/aloha-github-workflows/.github/actions/generate-version-file%' \
            .github/actions/aloha-github-workflows/.github/actions/asdf-install-and-cache/action.yml
      - name: Cache asdf tools
        uses: ./.github/actions/aloha-github-workflows/.github/actions/asdf-install-and-cache
  cache-pre-commit-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - name: Checkout voxel51/aloha-github-workflows
        uses: actions/checkout@v6.0.1
        with:
          repository: voxel51/aloha-github-workflows
          ref: main
          token: ${{ secrets.ORG_RO_ALOHA_GITHUB_WORKFLOWS_FG_PAT }}
          path: ./.github/actions/aloha-github-workflows
      - name: Set generate-version-file action's path from remote to local
        # Public repos cannot access private action repo without GitHub Enterprise
        # Instead, we clone the private workflow directory and update the `pre-commit-cache/action.yml`
        # file's reference to `voxel51/aloha-github-workflows/.github/actions/generate-version-file` with the local path.
        shell: bash
        run: |
          sed -i \
            's%voxel51/aloha-github-workflows/.github/actions/generate-version-file@main%./.github/actions/aloha-github-workflows/.github/actions/generate-version-file%' \
            .github/actions/aloha-github-workflows/.github/actions/pre-commit-cache/action.yml
      - name: Cache pre-commit repos
        uses: ./.github/actions/aloha-github-workflows/.github/actions/pre-commit-cache
